"""add seccion file videos

Revision ID: 97069841ecf3
Revises: 1f301c9fbb48
Create Date: 2025-01-24 14:15:32.932259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97069841ecf3'
down_revision = '1f301c9fbb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progreso')
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.drop_column('video_file')

    op.create_table('progreso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seccion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visto', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_visto', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], name='progreso_seccion_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='progreso_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='progreso_pkey')
    )
    # ### end Alembic commands ###
