"""Agregar columna estado_transferencia a la tabla venta

Revision ID: a2442f27d56f
Revises: bc4c330e7f20
Create Date: 2025-01-22 13:11:17.117050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2442f27d56f'
down_revision = 'bc4c330e7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_transferencia', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('estado_transferencia')

    # ### end Alembic commands ###
